language: python
python:
  - 3.7
resources:
  - name: nightly-trigger
    type: time
    seed:
      interval: "0 12 * * *"
jobs:
  - name: a4kScrapers_runCI
    type: runCI
    steps:
      - IN: nightly-trigger
      - IN: a4kScrapers_ciRepo
build:
  ci:
    - pip install -r requirements.txt
    - python -m unittest tests_runner.py
